### ISSUE TITLE
birthdaylist

### ISSUE THREAD

**Issue by lhops1339** [sdetweil/birthdaylist#1]
I have loaded your birthdaylist module into my Magic Mirror and have tried to run it.  Continue to get an error and MM will not come up.

**Comment by sdetweil** [comment]
what is the error?

**Comment by lhops1339** [comment]
This is on the MM window “Please create a config file or check the existing one for errors”
I have entered your sample code into the config file and saved it but continue getting the error. 
I did find that one of the curly brackets was missing and I replaced it 
But still error.

**Comment by sdetweil** [comment]
do
```
cd ~/MagicMirror
npm run config:check
```

report the error

**Comment by sdetweil** [comment]
fixed the sample syntax error

**Comment by lhops1339** [comment]
"your configuration file doesn't contain syntax errors :)"
This is the info after npm run config:check

**Comment by sdetweil** [comment]
ok, then npm start

**Comment by sdetweil** [comment]
and maybe ctrl-m to minimize mm
and see the messages from startup

**Comment by lhops1339** [comment]
Now I am only getting a black screen

**Comment by sdetweil** [comment]
ctrl-m to minimize

**Comment by sdetweil** [comment]
my guess is you missed an install step
```
git clone
cd birtdaylist
npm install
```

**Comment by lhops1339** [comment]
Okay I will do that again.

**Comment by sdetweil** [comment]
don't need to clone again

**Comment by lhops1339** [comment]
I must have screwed something else up because all I get now is a black screen.  but I did reload the birthdaylist files again.

**Comment by lhops1339** [comment]
I had a backup config file and now have the MM screen back.  But will have to start from scratch with the modes.  My original 
problem was the (tress) MktIndex stopped showing the market values but still has the layout.

**Comment by sdetweil** [comment]
need to look at the messages, black screen is almost always missing library

**Comment by lhops1339** [comment]
I was able to do a work around and found an other module to take care of the MktIndex issue.  But I saw your module for showing birthdays in the already installed calendar and that is what I am trying to do now.  But have not had much luck, but I appreciate your help for the birthdaylist problems I am having.

**Comment by sdetweil** [comment]
ok, but you need to post the messages so we can resolve the problem

**Comment by lhops1339** [comment]
okay...may take awhile because I am talking to you on my home computer and running the MM on the Raspberry pi.  May be able to get VNC working and make things much simpler.  One question that I have , will your birthdaylist program list the birthdays on the calendar screen like it does for the holidays?

**Comment by sdetweil** [comment]
I always use ssh.

you can also direct the messages to a file

npm start > somefile.txt

**Comment by sdetweil** [comment]
no this module has its own output window

**Comment by lhops1339** [comment]
Well I was hoping that it would show up int the calendar.  But would like to get it working.  I installed the the birthdaylist code into the MM config file and got a black screen.  Removed it and things are back to normal.  There must be a file or something that the birthdaylist config file is looking for that is causing the black screen.

**Comment by sdetweil** [comment]
it sounds like you did not do the npm install in the module folder

**Comment by lhops1339** [comment]
Just looked and birthdaylist is in the module folder

**Comment by sdetweil** [comment]
now, in terminal window 
```
cd ~/MagicMirror/modules/birthdaylist
npm install
```

**Comment by lhops1339** [comment]
I did a complete re install and not I think I have it.  Where do I put in my new birthdays and dates.  And I see that the language: "de" is that ok for me?

**Comment by sdetweil** [comment]
language de is German
data is in the file in the data folder

**Comment by lhops1339** [comment]
Should I change the language to us English...and if so what it the code?

**Comment by sdetweil** [comment]
en is english

**Comment by lhops1339** [comment]
This is what I see on the screenin the bottom_right corner  "27 in a white small box and then HHH HHHHH 21".
Where do I go to put in my data?

**Comment by sdetweil** [comment]
in the module folder is another folder named data. inside that is the bdl.csv file
bdl = BirthDayList

read the readme, sane as the page displayed for the module,  it says what to do.
![Screenshot_20230519_155609_Chrome](https://github.com/sdetweil/birthdaylist/assets/1498142/e26248d2-10cb-4460-89f6-3cb5ee2b4ba3)

**Comment by lhops1339** [comment]
when I click on bdl.csv I get a program loads named LiberOffice....not sure what to do at that point.

**Comment by sdetweil** [comment]
it's a spreadsheet program

I'd just use a text editor.
csv is all text

**Comment by lhops1339** [comment]
ok got it

**Comment by lhops1339** [comment]
Okay I have changed two columns in row 2 and 3 but I see nothing on the screen when I start MM

**Comment by sdetweil** [comment]
show me the file contents

**Comment by lhops1339** [comment]
![20230519_172009](https://github.com/sdetweil/birthdaylist/assets/90342426/91565424-d32f-467c-88d3-922ce1e628cd)

**Comment by sdetweil** [comment]
can u show me the csv file in a text editor, like nano..

**Comment by sdetweil** [comment]
I have a high school graduation to go to in an hour or so, no time til after 10pm central. traveling home all day tomorrow

**Comment by lhops1339** [comment]
Thanks for your help....I will work with it and get in touch in a day or two.

**Comment by lhops1339** [comment]
Sam,  I finely realized that if the birthday is not in the present month it will not show on the screen.  I have loaded all the birthdays in the csv file and have things working well.  I want to thank you for all your help.  One other thing ....is it worth updating my Magic Mirror program?  Last time I did a few modules stop working.
